---
version: "2"

services:
  terraform:
    image: zenika/terraform-azure-cli:r4.1-tf0.12.26-azcli2.7.0
    volumes:
      - .:/workspace
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
